version: "3"

networks:
  net.prod:
    external: true

services:
  postal:
    image: wumvi/email.prod
    container_name: email.prod
    networks:
      net.prod: {}
    volumes:
      - /root/data/email/postal:/opt/postal/config
      - /root/data/email/docker:/docker
    environment:
      - MYSQL_ROOT_PASSWORD=changeme
      - MYSQL_DATABASE=postal
      - RABBITMQ_DEFAULT_USER=postal
      - RABBITMQ_DEFAULT_PASS=changeme
      - RABBITMQ_DEFAULT_VHOST=postal

  mysql:
    image: mariadb:10
    container_name: postal_mysql
    networks:
      net.prod: {}
    volumes:
      - /root/data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=changeme
      - MYSQL_DATABASE=postal

  rabbitmq:
    image: rabbitmq:3-alpine
    container_name: postal_rabbitmq
    networks:
      net.prod: {}
    environment:
      - RABBITMQ_DEFAULT_USER=postal
      - RABBITMQ_DEFAULT_PASS=changeme
      - RABBITMQ_DEFAULT_VHOST=/postal